import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header/header";

export const metadata: Metadata = {
  title: "Car Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
